# xboard73 (nRF52840) Kconfig

# 启用 BLE 键盘 HID
CONFIG_ZMK_BLE=y
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_ZMK_HID_USAGE_PAGE_KEYBOARD=y

# 低功耗
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_BT_CTLR_SDC_RADIO_IRQ_PRIO=0
CONFIG_ZMK_SLEEP=y

# 电池电压检测 (通过 ADC)
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ADC=y
CONFIG_ZMK_BATTERY_VOLTAGE_DIVIDER=y

# 矩阵扫描参数
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10

# 输出
CONFIG_ZMK_WINK=n
CONFIG_ZMK_AUDIO=n
CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_ZMK_BACKLIGHT=n

# 调试
CONFIG_CONSOLE=n
CONFIG_SERIAL=n
